"use client";

import React, { useState } from "react";
import {
    FileText,
    BarChart3,
    PieChart,
    Calendar,
    Users,
    Download,
    ExternalLink,
    TrendingUp,
    ChevronRight,
    Search,
    Filter,
    Table as TableIcon
} from "lucide-react";
import DashboardLayout from "@/components/layout/DashboardLayout";

const REPORT_TYPES = [
    { title: "Attendance Insights", description: "Detailed branch attendance trends and punctuality logs.", icon: BarChart3, color: "bg-emerald-500", count: "14 Reports" },
    { title: "Workforce Analytics", description: "Employee distribution by department and designation.", icon: PieChart, color: "bg-indigo-500", count: "6 Reports" },
    { title: "Leave Summary", description: "Monthly leave patterns and pending request statistics.", icon: FileText, color: "bg-amber-500", count: "12 Reports" },
];

export default function BranchReports() {
    const [selectedReport, setSelectedReport] = useState<string | null>(null);

    return (
        <DashboardLayout>
            <div className="space-y-8">
                {/* Header */}
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                    <div>
                        <h1 className="text-3xl font-black text-slate-900 tracking-tight">Intelligence & Reports</h1>
                        <p className="text-slate-500 font-medium mt-1">Strategic data insights for your branch</p>
                    </div>
                </div>

                {/* Report Categories */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    {REPORT_TYPES.map((type) => (
                        <div key={type.title} className="bg-white p-8 rounded-[40px] border border-slate-100 shadow-sm transition-all hover:shadow-xl hover:-translate-y-1 group">
                            <div className="flex items-center justify-between mb-8">
                                <div className={`w-14 h-14 ${type.color} text-white rounded-2xl flex items-center justify-center shadow-lg group-hover:scale-110 transition-transform`}>
                                    <type.icon className="w-7 h-7" />
                                </div>
                                <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{type.count}</span>
                            </div>
                            <h3 className="text-xl font-bold text-slate-900 tracking-tight mb-2">{type.title}</h3>
                            <p className="text-sm text-slate-500 font-medium leading-relaxed mb-8">{type.description}</p>
                            <button className="w-full py-4 bg-slate-50 border border-slate-100 text-slate-700 rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-slate-900 hover:text-white transition-all">
                                Explore Analytics
                            </button>
                        </div>
                    ))}
                </div>

                {/* Recent Generated Reports Table */}
                <div className="bg-white rounded-[40px] border border-slate-100 shadow-sm overflow-hidden pb-4">
                    <div className="p-8 border-b border-slate-50 flex items-center justify-between flex-wrap gap-4">
                        <div>
                            <h2 className="text-xl font-bold text-slate-900 tracking-tight">Recent Archives</h2>
                            <p className="text-sm text-slate-500 font-medium mt-1">Access previously generated branch data reports</p>
                        </div>
                        <div className="flex items-center gap-2">
                            <div className="relative">
                                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                                <input type="text" placeholder="Search archive..." className="bg-slate-50 border-none rounded-2xl py-2 pl-9 pr-4 text-xs font-bold w-48" />
                            </div>
                            <button className="p-2 bg-slate-50 rounded-xl text-slate-400 hover:bg-slate-100">
                                <Filter className="w-4 h-4" />
                            </button>
                        </div>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="w-full text-left">
                            <thead>
                                <tr className="text-[10px] font-black text-slate-300 uppercase tracking-widest border-b border-slate-50">
                                    <th className="px-8 py-5">Report Name</th>
                                    <th className="px-6 py-5">Generated By</th>
                                    <th className="px-6 py-5">Period</th>
                                    <th className="px-8 py-5 text-right">Download</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-50">
                                {[
                                    { name: "Monthly Attendance Summary - Jan 2026", type: "PDF", owner: "System Auto", period: "Jan 01 - Jan 12", size: "1.2 MB" },
                                    { name: "Department Workforce Distribution", type: "XLSX", owner: "Branch Admin", period: "Real-time", size: "450 KB" }
                                ].map((report, i) => (
                                    <tr key={i} className="group hover:bg-slate-50/50 transition-colors">
                                        <td className="px-8 py-5">
                                            <div className="flex items-center gap-4">
                                                <div className="w-10 h-10 bg-indigo-50 text-indigo-500 rounded-xl flex items-center justify-center font-black text-xs">
                                                    {report.type}
                                                </div>
                                                <div>
                                                    <p className="text-sm font-bold text-slate-900 leading-tight group-hover:text-indigo-600 transition-colors">{report.name}</p>
                                                    <p className="text-[10px] font-bold text-slate-400 mt-1 uppercase tracking-tight">{report.size}</p>
                                                </div>
                                            </div>
                                        </td>
                                        <td className="px-6 py-5">
                                            <p className="text-xs font-bold text-slate-600">{report.owner}</p>
                                            <p className="text-[10px] text-slate-400 font-medium">Platform Service</p>
                                        </td>
                                        <td className="px-6 py-5">
                                            <p className="text-xs font-bold text-slate-700">{report.period}</p>
                                        </td>
                                        <td className="px-8 py-5 text-right">
                                            <button className="p-2 text-slate-400 hover:text-indigo-600 transition-colors">
                                                <Download className="w-5 h-5" />
                                            </button>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>

                {/* Insight Banner */}
                <div className="bg-gradient-to-r from-emerald-600 to-teal-700 rounded-[40px] p-10 text-white flex flex-col md:flex-row items-center justify-between gap-8 shadow-xl shadow-emerald-100">
                    <div className="max-w-md">
                        <TrendingUp className="w-12 h-12 text-emerald-200/50 mb-4" />
                        <h3 className="text-2xl font-black tracking-tight mb-2">Performance Spike!</h3>
                        <p className="text-emerald-50/80 font-medium leading-relaxed">Your branch attendance has improved by 4% this week. Generate a deeper insight report to see which department contributed most.</p>
                    </div>
                    <button className="px-8 py-5 bg-white text-emerald-700 rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-emerald-50 transition-all shadow-2xl flex items-center gap-3">
                        <BarChart3 className="w-4 h-4" />
                        Generate Custom Report
                    </button>
                </div>
            </div>
        </DashboardLayout>
    );
}
