import { z } from 'zod';

export const vendorApplicationSchema = z.object({
    date: z.string(),
    company_id: z.number(),
    branch_id: z.number().optional().nullable(),
    category: z.string().optional().nullable(),
    categoryname: z.string().optional().nullable(),
    vendor_name: z.string().min(1, 'Vendor name is required'),
    company_name: z.string().min(1, 'Company name is required'),
    company_address: z.string().min(1, 'Company address is required'),
    email: z.string().email('Invalid email address'),
    phone_number: z.string().min(10, 'Phone number must be at least 10 digits'),
    appointment_status: z.enum(['yes', 'no']),
    business_type: z.enum(['supplier', 'distributor', 'service-provider', 'manufacturer', 'others']),
    upload_file_url: z.string().optional().nullable(),
    remarks: z.string().optional().nullable(),
});



export const jobSeekerApplicationSchema = z.object({
    date: z.string(),
    company_id: z.number(),
    branch_id: z.number().optional().nullable(),
    category: z.string().optional().nullable(),
    categoryname: z.string().optional().nullable(),
    full_name: z.string().min(1, 'Full name is required'),
    gender: z.enum(['male', 'female', 'other', 'prefer-not-to-say']),
    dob: z.string(),
    age: z.coerce.number().min(1).max(120),
    address: z.string().min(1, 'Address is required'),
    blood_group: z.string(),
    contact_number: z.string().min(10),
    email: z.string().email(),
    qualification: z.enum(['10th', '12th', 'diploma', 'ug', 'pg', 'phd']),
    department: z.enum(['hr', 'it', 'marketing', 'finance', 'sales', 'production', 'others']),
    years_of_experience: z.enum(['fresher', '1-2', '3-5', '5+']),
    preferred_job_type: z.enum(['full-time', 'part-time', 'hybrid', 'remote']),
    upload_resume_url: z.string().optional().nullable(),
    remarks: z.string().optional().nullable(),
});

export const internshipApplicationSchema = z.object({
    date: z.string(),
    company_id: z.number(),
    branch_id: z.number().optional().nullable(),
    category: z.string().optional().nullable(),
    categoryname: z.string().optional().nullable(),
    full_name: z.string().min(1),
    registration_number: z.string().min(1),
    address: z.string().min(1),
    email: z.string().email(),
    contact_number: z.string().min(10),
    blood_group: z.string(),
    dob: z.string(),
    age: z.coerce.number().min(1).max(120),
    gender: z.enum(['male', 'female', 'other', 'prefer-not-to-say']),
    college_institution_name: z.string().min(1),
    course_type: z.enum(['ug', 'pg', 'certification']),
    department: z.enum(['computer-science', 'electrical', 'mechanical', 'civil', 'electronics', 'business', 'others']),
    internship_domain: z.enum(['it', 'non-it', 'others']),
    duration: z.enum(['3-months', '6-months']),
    upload_file_url: z.string().optional().nullable(),
    remarks: z.string().optional().nullable(),
});

export const careerGuidanceSchema = z.object({
    date: z.string(),
    company_id: z.coerce.number(),
    branch_id: z.coerce.number().optional().nullable(),
    category: z.string().optional().nullable(),
    categoryname: z.string().optional().nullable(),
    student_name: z.string().optional().nullable(),
    candidate_name: z.string().optional().nullable(),
    standard_year: z.string().optional().nullable(),
    education_level: z.string().optional().nullable(),
    institution_name: z.string().optional().nullable(),
    date_of_birth: z.string().optional().nullable(),
    age: z.coerce.number().optional().nullable(),
    gender: z.string().optional().nullable(),
    location: z.string().optional().nullable(),
    city: z.string().optional().nullable(),
    pincode: z.string().optional().nullable(),
    contact_number: z.string().optional().nullable(),
    email: z.string().optional().nullable(),
    parent_guardian_name: z.string().optional().nullable(),
    studies_preference: z.string().optional().nullable(),
    current_stream: z.string().optional().nullable(),
    last_exam_result: z.string().optional().nullable(),
    well_performing_subjects: z.string().optional().nullable(),
    favorite_subject: z.string().optional().nullable(),
    struggle_subject: z.string().optional().nullable(),
    enjoyed_activities: z.string().optional().nullable(),
    prefer_working_with: z.string().optional().nullable(),
    solve_problems_logically: z.string().optional().nullable(),
    enjoy_creative_tasks: z.string().optional().nullable(),
    test_reason: z.string().optional().nullable(),
    comfortable_with_assessments: z.string().optional().nullable(),
    abroad_local: z.string().optional().nullable(),
    preferred_country: z.string().optional().nullable(),
    city_if_abroad: z.string().optional().nullable(),
    preferred_university: z.string().optional().nullable(),
    career_interest: z.string().optional().nullable(),
    career_goal: z.string().optional().nullable(),
    skills_strengths: z.string().optional().nullable(),
    academic_performance: z.string().optional().nullable(),
    hobbies_extracurricular: z.string().optional().nullable(),
    preferred_mode_of_study: z.string().optional().nullable(),
    counselling_mode: z.string().optional().nullable(),
    preferred_language: z.string().optional().nullable(),
    session_expectations: z.string().optional().nullable(),
    career_support_duration: z.string().optional().nullable(),
    mentorship_required: z.string().optional().nullable(),
    remarks_notes: z.string().optional().nullable(),

    // Study Abroad Specific
    current_qualification: z.string().optional().nullable(),
    highest_qualification_completed: z.string().optional().nullable(),
    academic_score_gpa: z.string().optional().nullable(),
    medium_of_instruction: z.string().optional().nullable(),
    intended_level_of_study: z.string().optional().nullable(),
    english_test_status: z.string().optional().nullable(),
    target_intake_year: z.string().optional().nullable(),
    budget_range: z.string().optional().nullable(),
});

export const courseEnquirySchema = z.object({
    date: z.string(),
    company_id: z.number(),
    branch_id: z.number().optional().nullable(),
    category: z.string().min(1),
    sub_category: z.string().min(1),
    name: z.string().min(1),
    email: z.string().email(),
    phone_number: z.string().min(10),
    date_of_birth: z.string(),
    age: z.coerce.number(),
    address: z.string().min(1),
    course_enquiry: z.string().min(1),
    remarks: z.string().optional().nullable(),
});
